name: madad_advice
description: A new Flutter project.
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^1.1.6
  pin_code_fields: ^4.0.0
  #intl_phone_field: ^1.3.0
  #intl_phone_number_input: ^0.4.6+2
  easy_localization_loader: ^0.0.2
  easy_localization: ^2.3.2
  #mask_text_input_formatter: ^1.0.7
  dots_indicator: ^1.1.0
  url_launcher: ^5.4.1
  provider: ^3.2.0
  flare_flutter: ^2.0.5
  intl: ^0.16.0
  cached_network_image: ^2.0.0-rc
  http: ^0.12.0+3
  shared_preferences: ^0.5.6+1
  pull_to_refresh: ^1.6.1
  md2_tab_indicator: ^1.0.2
  flutter_html: ^1.0.0
  shimmer: ^1.0.1
  share: ^0.6.3+5
  flutter_icons: ^1.0.0+1
  introduction_screen: ^1.0.7
  connectivity: ^0.4.6+2
  #launch_review: ^2.0.0
  toast: ^0.1.5
  #badges: ^1.1.1
  flutter_staggered_animations: ^0.1.2
  modal_bottom_sheet: ^0.2.0+1
  #toggle_switch: "^0.1.5"
  image_picker: ^0.6.7+4
  expandable: ^4.1.4
  #webview_flutter: ^0.3.22+1
  dio: ^3.0.9
  json_annotation: ^3.0.1
  move_to_background: ^1.0.1
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  liquid_pull_to_refresh: ^2.0.0
  open_file: ^3.0.1
  path_provider: ^1.6.11
  percent_indicator: "^2.1.5"
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4+2
  progress_indicators: ^0.1.5
  rxdart: ^0.24.1
  firebase_core: ^0.4.5
  file_picker: ^1.13.2
  flutter_svg: ^0.17.4
  rate_my_app: ^0.7.0+1
  font_awesome_flutter:
    git:
      url: https://github.com/handzup/font_awesome_flutter.git

  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: ^1.10.1
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5
  json_serializable: ^3.3.0
  hive_generator: ^0.7.1
  get_it: ^4.0.4
  flutter_test:
    sdk: flutter



flutter_native_splash:
  image: assets/logo.png
  color: "ffffff"

module:

  androidX: true 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  image_path_ios: 'assets/1024.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/news1.png
    - assets/news2.png
    - assets/news3.png
    - assets/news4.png
    - assets/news5.png
    - assets/news6.png
    - assets/news7.png
    - assets/splash.png
    - assets/icon.png
    - assets/logo.png
    - assets/1024.png
    - assets/madad-logo.png
    - assets/loader.flr
    - assets/loading_rainbow.flr
    - resources/langs/
  fonts:
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
          




    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
 